# Recommendation Notebook

In [41]:
print("""
====================================
Xecomerce Recommendation System
====================================
""")

====================================
Xecomerce Recommendation System
====================================

In [42]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import (
    TfidfVectorizer
)

from sklearn.metrics.pairwise import (
    cosine_similarity
)

import warnings

warnings.filterwarnings("ignore")

In [43]:
products = pd.read_csv(
    "../datasets/products.csv"
)

print(
    f"Products Loaded: {len(products)}"
)

Products Loaded: 1465

In [44]:
products.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [45]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: object(16)
memory usage: 183.3+ KB

In [46]:
products = products[
    [
        "product_name",
        "category",
        "about_product",
        "rating"
    ]
]

products.head()

,product_name,category,about_product,rating
0,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,High Compatibility : Compatible With iPhone 12...,4.2
1,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,"Compatible with all Type C enabled devices, be...",4.0
2,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,【 Fast Charger& Data Sync】-With built-in safet...,3.9
3,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,The boAt Deuce USB 300 2 in 1 cable is compati...,4.2
4,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,[CHARGE & SYNC FUNCTION]- This cable comes wit...,4.2

In [47]:
products.isnull().sum()

product_name     0
category         0
about_product    0
rating           0
dtype: int64

In [48]:
products["about_product"] = (
    products["about_product"]
    .fillna("")
)

products["category"] = (
    products["category"]
    .fillna("")
)

In [49]:
products["combined_features"] = (

    products["product_name"]

    + " "

    + products["category"]

    + " "

    + products["about_product"]

)

In [50]:
products[
    [
        "product_name",
        "combined_features"
    ]
].head()

,product_name,combined_features
0,Wayona Nylon Braided USB to Lightning Fast Cha...,Wayona Nylon Braided USB to Lightning Fast Cha...
1,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...
2,Sounce Fast Phone Charging Cable & Data Sync U...,Sounce Fast Phone Charging Cable & Data Sync U...
3,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...
4,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Portronics Konnect L 1.2M Fast Charging 3A 8 P...

In [51]:
vectorizer = TfidfVectorizer(
    stop_words="english",
    max_features=10000
)

feature_vectors = vectorizer.fit_transform(
    products["combined_features"]
)

print(
    feature_vectors.shape
)

(1465, 10000)

In [52]:
similarity = cosine_similarity(
    feature_vectors
)

print(
    similarity.shape
)

(1465, 1465)

In [53]:
product_index = pd.Series(
    products.index,
    index=products["product_name"]
)

product_index.head()

product_name
Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)                                         0
Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)          1
Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices                                                                   2
boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant, Tangle-Free, Sturdy Cable with 3A Fast Charging & 480mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Martian Red)    3
Portronics Konnect L 1.2M Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function for iPhone, iPad (Grey)                                                                                             4
dtype: int64

In [54]:
def recommend_products(
    product_name,
    top_n=5
):

    if product_name not in product_index:

        print(
            "Product Not Found"
        )

        return

    idx = product_index[
        product_name
    ]

    similarity_scores = list(
        enumerate(
            similarity[idx]
        )
    )

    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    similarity_scores = similarity_scores[
        1 : top_n + 1
    ]

    product_indices = [

        i[0]

        for i in similarity_scores

    ]

    return products.iloc[
        product_indices
    ][
        [
            "product_name",
            "category",
            "rating"
        ]
    ]

In [55]:
products["product_name"].iloc[0]

'Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)'

In [56]:
products["product_name"].duplicated().sum()

np.int64(128)

In [57]:
product_index = {}

for idx, product in enumerate(
    products["product_name"]
):
    if product not in product_index:
        product_index[product] = idx

In [58]:
products[
    products["product_name"]
    .str.contains(
        "Samsung",
        case=False,
        na=False
    )
][
    [
        "product_name"
    ]
].head(10)

                                          product_name
22   Samsung 80 cm (32 Inches) Wondertainment Serie...
32   Zoul USB C 60W Fast Charging 3A 6ft/2M Long Ty...
33   Samsung Original Type C to C Cable - 3.28 Feet...
48   7SEVEN® Compatible for Samsung Smart 4K Ultra ...
61   Samsung 108 cm (43 inches) Crystal 4K Neo Seri...
70   oraimo 65W Type C to C Fast Charging Cable USB...
84   Wayona Usb Type C Fast Charger Cable Fast Char...
87   Samsung 108 cm (43 inches) Crystal 4K Series U...
102  Isoelite Remote Compatible for Samsung LED/LCD...
105  Wayona Type C To Type C Long Fast Charging Cab...

In [59]:
recommend_products(
    "Samsung Galaxy M33 5G"
)

Product Not Found

In [60]:
products["rating"] = pd.to_numeric(
    products["rating"],
    errors="coerce"
)

products.sort_values(
    by="rating",
    ascending=False
)[
    [
        "product_name",
        "rating"
    ]
].head(10)

                                           product_name  rating
174   Syncwire LTG to USB Cable for Fast Charging Co...     5.0
324   REDTECH USB-C to Lightning Cable 3.3FT, [Apple...     5.0
775   Amazon Basics Wireless Mouse | 2.4 GHz Connect...     5.0
1299  Instant Pot Air Fryer, Vortex 2QT, Touch Contr...     4.8
1201  Oratech Coffee Frother electric, milk frother ...     4.8
1145  Swiffer Instant Electric Water Heater Faucet T...     4.8
1223  FIGMENT Handheld Milk Frother Rechargeable, 3-...     4.7
1226  Zuvexa USB Rechargeable Electric Foam Maker - ...     4.7
1275  Multifunctional 2 in 1 Electric Egg Boiling St...     4.7
459   Spigen EZ Fit Tempered Glass Screen Protector ...     4.7

In [61]:
products[
    "category"
].value_counts().head(10)

category
Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables                        233
Electronics|WearableTechnology|SmartWatches                                                               76
Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|Smartphones                                      68
Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions                                             63
Electronics|Headphones,Earbuds&Accessories|Headphones|In-Ear                                              52
Electronics|HomeTheater,TV&Video|Accessories|RemoteControls                                               49
Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|MixerGrinders                                  27
Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Mice                            24
Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables                                            24
Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|DryIrons     24
Name: count, dtype: int64

In [62]:
category = "Electronics"

products[
    products["category"]
    .str.contains(
        category,
        case=False,
        na=False
    )
][
    [
        "product_name",
        "rating"
    ]
].head(10)

                                         product_name  rating
12  AmazonBasics Flexible Premium HDMI Cable (Blac...     4.4
16  MI 80 cm (32 inches) 5A Series HD Ready Smart ...     4.2
19  LG 80 cm (32 inches) HD Ready Smart LED TV 32L...     4.3
21  tizum HDMI to VGA Adapter Cable 1080P for Proj...     3.7
22  Samsung 80 cm (32 Inches) Wondertainment Serie...     4.3
24  Acer 80 cm (32 inches) I Series HD Ready Andro...     4.3
25  Tizum High Speed HDMI Cable with Ethernet | Su...     4.2
26  OnePlus 80 cm (32 inches) Y Series HD Ready LE...     4.2
38  OnePlus 126 cm (50 inches) Y Series 4K Ultra H...     4.2
41  Mi 108 cm (43 inches) Full HD Android LED TV 4...     4.3

In [63]:
import joblib

joblib.dump(
    vectorizer,
    "../saved_models/recommendation_vectorizer.pkl"
)

joblib.dump(
    similarity,
    "../saved_models/recommendation_similarity.pkl"
)

print(
    "Recommendation Model Saved Successfully"
)

Recommendation Model Saved Successfully

In [64]:
import os

os.listdir(
    "../saved_models"
)

['chatbot_index.pkl',
 'dataset_profiles.pkl',
 'demand_forecast.pkl',
 'fake_review.pkl',
 'fake_review_vectorizer.pkl',
 'price_predictor.pkl',
 'products.faiss',
 'products.faiss.meta',
 'recommendation_similarity.pkl',
 'recommendation_vectorizer.pkl',
 'recommender.pkl',
 'sentiment.pkl',
 'sentiment_vectorizer.pkl']

In [65]:
print("""
Recommendation Notebook Completed

✔ Dataset Loaded
✔ Feature Engineering
✔ TF-IDF Vectorization
✔ Similarity Matrix Created
✔ Product Recommendation Generated
✔ Recommendation Model Saved
""")

Recommendation Notebook Completed

✔ Dataset Loaded
✔ Feature Engineering
✔ TF-IDF Vectorization
✔ Similarity Matrix Created
✔ Product Recommendation Generated
✔ Recommendation Model Saved